Vagrant.configure("2") do |config|
  box_file = ENV.fetch("BOX_FILE", "builds/virtualbox-rhel9.box")

  # control
  config.vm.define "ctl" do |m|
    m.vm.box = box_file
    m.vm.hostname = "ctl"
    m.vm.network "private_network", ip: "10.10.10.10"
  end

  # node1
  config.vm.define "node1" do |m|
    m.vm.box = box_file
    m.vm.hostname = "node1"
    m.vm.network "private_network", ip: "10.10.10.11"
  end

  config.vm.provider :virtualbox do |vb|
    vb.memory = ENV.fetch("MEM", "3072")
    vb.cpus   = ENV.fetch("CPU", "2")
  end
end
