Vagrant.configure("2") do |config|
  OS_VERSION = ENV.fetch("OS_VERSION", "9")
  BOX_NAME   = ENV.fetch("BOX_NAME", "labctl-rhel#{OS_VERSION}")
  BOX_PATH   = File.expand_path("../packer/builds/virtualbox-rhel#{OS_VERSION}.box", __dir__)

  # Auto-add the local box if not present
  config.vm.box     = BOX_NAME
  config.vm.box_url = "file://#{BOX_PATH}"
  config.vm.synced_folder '.', '/vagrant', disabled: true

  # ctl
  config.vm.define "ctl" do |m|
    m.vm.hostname = "ctl"
    m.vm.network "private_network", ip: "10.10.10.10"
  end

  # node1
  config.vm.define "node1" do |m|
    m.vm.hostname = "node1"
    m.vm.network "private_network", ip: "10.10.10.11"
  end

  config.vm.provider :virtualbox do |vb|
    vb.memory = ENV.fetch("MEM", "3072")
    vb.cpus   = ENV.fetch("CPU", "2")
  end
end
