#!/usr/bin/env bash
set -euo pipefail

# Allow overriding the list path: ./scripts/setup-vagrant-registration.sh --list path/to/list
PLUGINS_FILE="${PLUGINS_FILE:-vagrant-plugins.list}"
if [[ "${1:-}" == "--list" && -n "${2:-}" ]]; then
  PLUGINS_FILE="$2"
fi

GLOBAL_VAGRANTFILE="$HOME/.vagrant.d/Vagrantfile"

echo "==> labctl: Vagrant registration setup"

# 1) Install plugins from the list file
if [[ -f "$PLUGINS_FILE" ]]; then
  echo "==> Installing required Vagrant plugins from $PLUGINS_FILE ..."
  while IFS= read -r plugin; do
    [[ -z "$plugin" || "$plugin" =~ ^# ]] && continue
    if vagrant plugin list | grep -qE "^${plugin}\b"; then
      echo "   ✓ $plugin already installed"
    else
      echo "   → Installing $plugin"
      vagrant plugin install "$plugin"
    fi
  done < "$PLUGINS_FILE"
else
  echo "WARNING: $PLUGINS_FILE not found; skipping plugin install step"
fi

# 2) Prompt for RHSM values
echo
echo "==> RHSM registration (activation key recommended)"
read -rp "   Organization (ORG): " RHSM_ORG
read -rp "   Activation Key: " RHSM_ACTIVATION_KEY
read -rp "   Satellite/Server (optional, press Enter to skip): " RHSM_SERVER
echo

# 3) Create/backup ~/.vagrant.d/Vagrantfile
mkdir -p "$(dirname "$GLOBAL_VAGRANTFILE")"
if [[ -f "$GLOBAL_VAGRANTFILE" ]]; then
  cp -f "$GLOBAL_VAGRANTFILE" "$GLOBAL_VAGRANTFILE.bak.$(date +%Y%m%d-%H%M%S)"
  echo "==> Backed up existing Vagrantfile to: $GLOBAL_VAGRANTFILE.bak.*"
fi

cat > "$GLOBAL_VAGRANTFILE" <<RUBY
# -*- mode: ruby -*-
# vi: set ft=ruby :
# Generated by labctl/scripts/setup-vagrant-registration.sh

Vagrant.configure("2") do |config|
  config.ssh.insert_key = false
  config.vm.synced_folder ".", "/vagrant", disabled: true

  if Vagrant.has_plugin?("vagrant-registration")
    config.registration.manager = "subscription_manager"
    config.registration.org = "${RHSM_ORG}"
    config.registration.activationkey = "${RHSM_ACTIVATION_KEY}"
    config.registration.auto_attach = true
    config.registration.unregister_on_halt = true
    #{RHSM_SERVER:+config.registration.server = "${RHSM_SERVER}"}
  end

  if Vagrant.has_plugin?("vagrant-vbguest")
    config.vbguest.auto_update = false
  end
end
RUBY

echo "==> Wrote $GLOBAL_VAGRANTFILE"
echo "All set. Next: cd vagrant && vagrant up"
